### ISSUE TITLE
When you /varset SomeVariable ${Me.Y}, ${Me.X}, or ${Me.Z} the value of ${SomeVariable} may differ by 0.01

### ISSUE THREAD

**Issue by ghost** [macroquest/macroquest2#13]
This does not happen with VeryVanilla. Code to replicate:

`| With MQNext the float variables that are set using ${Me.X}, ${Me.Y}, ${Me.Z}
| may differ by 0.01. This does not happen with VeryVanilla.
|
| Blunt explanation: When you set a variable to 0.01, you expect to retrieve the
| variable as 0.01, not 0.00 or 0.02
|
| Use the following to see for yourself how it behaves. Move somewhere, remain
| stationary. Move somewhere else.
|
| My belief is the issue lies with a type conversion / rounding rule. It probably
| is widespread.
|
Sub Main

    /declare SomeXPosition float outer 0.00
    /declare SomeYPosition float outer 0.00
    /declare SomeZPosition float outer 0.00

    /while (1) {

        /varset SomeXPosition ${Me.X}
        /varset SomeYPosition ${Me.Y}
        /varset SomeZPosition ${Me.Z}

        /echo X: SomeXPosition ${SomeXPosition} Me.X ${Me.X}
        /echo Y: SomeYPosition ${SomeYPosition} Me.Y ${Me.Y}
        /echo Z: SomeZPosition ${SomeZPosition} Me.Z ${Me.Z}
        /echo
        /delay 5s
      
    }

/return`

**Comment by brainiac** [comment]
I think you're looking for https://gitlab.com/macroquest/next/mqnext/-/issues

This repository is not monitored for issues
