### ISSUE TITLE
Formerly ${Task[0]} would return the current task

### ISSUE THREAD

**Issue by ghost** [macroquest/macroquest2#14]
On VeryVanilla, ${Task[0]} would return the current task. ${Task[1]} would also return the current task.  Now NULL is returned with ${Task[0]}.

May not be an "issue", but thought it was worth reporting as a difference in behavior.

**Comment by brainiac** [comment]
I think you're looking for https://gitlab.com/macroquest/next/mqnext/-/issues. This repository is not monitored for issues
